# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  install:
    cmds:
      - sh ./scripts/install/docker.sh
      - sh ./scripts/install/nodejs.sh
      - npm install
      - npm run setup